name: Secret scan

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  gitleaks-scan:
    name: Scan repository for secrets with gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run gitleaks secret scan
        uses: zricethezav/gitleaks-action@v8
        with:
          # Exit non-zero if secrets are found
          args: '--redact --exit-code 1'
